### ISSUE TITLE
This could perhaps be easily ported into a vertical bookmarks bar :)

### ISSUE THREAD

**Issue by EC-O-DE** [Kiuryy/Leftside_Back#1]
This could perhaps be easily ported into a vertical bookmarks bar :) With only website icons/favicons auto hovering in and out from side with the background.

**Comment by Kiuryy** [comment]
I think this is not the extension you meant :)
Anyway, I heard from some people already that they want to have such a sidebar. Currently I don't have plans to make a version with icons only, because this would require a major redesign of the extension (flyout directories vs. nested lists).
This would rather fit as a separate extension, but I don't have the time to build something like this, I'm completely busy with the sidebar extension already.
